Draft roadmap
pangeo-data/pangeo pull request #906
Opened 2023-05-27 21:35 UTC by abarciauskas-bgse

2023-07-10 00:23 UTC, paigem requested changes
Thank you @abarciauskas-bgse for creating this document and laying the groundwork for the Pangeo roadmap. I made several suggested updates to expand on your points and emphasize the unique position that Pangeo is in and how we can leverage that to move forward.

Happy to discuss any of these points @abarciauskas-bgse or anyone else who wants to comment!

2023-07-10 00:23 UTC, paigem commented on docs/roadmap.rst
> +1. Setting higher level goals to guide the community in development and in writing proposals. For example, Pangeo advocates for the use of STAC to facilitate access to data. We believe setting higher
```suggestion
1. _Advocate for new directions and best practices in the development of new tools, maintenance of existing tools, and the use of these tools in a geoscience context_: Advocacy will be driven by community input via community forums (e.g. Pangeo meetings or Discourse). We believe that establishing and communicating community-accepted conventions and best-practices is necessary for cross-platform collaboration as the landscape of resources continuously evolves. A current example is the Pangeo advocacy for the use of STAC to facilitate access to datasets.
```

2023-07-10 19:23 UTC, jmunroe commented
This might be too tactical, but is applying for funding like [NSF POSE](https://new.nsf.gov/funding/opportunities/pathways-enable-open-source-ecosystems-pose) (due September 7, 2023) be on the roadmap?

2023-07-10 21:53 UTC, paigem commented
Thanks for your comment @jmunroe, and you bring up a good point! Should our Roadmap include a mention of writing funding proposals? That's certainly something we will need to do as a community. Since funding spans both (1) supporting the community and (2) supporting software, perhaps we can add a sentence about funding at the top of the roadmap?

Our first thought was to keep this roadmap pretty general, so my inclination is to not mention a specific funding call, but I'm open to adding it here if you think it makes sense @jmunroe.

2023-07-11 02:11 UTC, jmunroe commented
A general roadmap is probably wiser than listing any specific funding calls. 

I agree that hiring a person makes sense as a goal. I'd advocate for a 'Community Manager' rather than (only) a 'Communications Manager' and include in the roadmap seeking funding to support that person full time.

2023-07-11 02:16 UTC, paigem commented
@jmunroe I completely agree with the term "community manager", and indicated as such in my review of this PR. 😉

I can add a sentence about applying for funding to support the community manager.

2023-07-14 19:52 UTC, paigem approved these changes

2023-07-14 19:55 UTC, merged